global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'service-scrape'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'service:8080' ]
    basic_auth:
      username: 'prometheus'
      password: 'prometheus'

  - job_name: 'rabbitmq-scrape'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'rabbitmq:15692' ]
    basic_auth:
      username: 'rabbitmq'
      password: 'rabbitmq'